[package]
name = "dmd"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2"
ethstore = { path = "../../../../../accounts/ethstore"}
parity-crypto = { path = "../../../../../parity-crypto" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
